files:
  - source: '*.po'
    ignore:
      - '*ca.po'
      - '*co.po'
      - '*cs.po'
      - '*da.po'
      - '*de.po'
      - '*es.po'
      - '*fi.po'
      - '*fr.po'
      - '*he.po'
      - '*hu.po'
      - '*id.po'
      - '*it.po'
      - '*ja.po'
      - '*ko.po'
      - '*lt.po'
      - '*ru.po'
      - '*nl.po'
      - '*no.po'
      - '*pl.po'
      - '*pb.po'
      - '*tr.po'
      - '*pt.po'
      - '*pt_BR.po'
      - '*ro.po'
      - '*sk.po'
      - '*sl.po'
      - '*ua.po'
      - '*uk.po'
      - '*zh_CN.po'
      - '*zh_TW.po'
      - '*bg.po'
      - '*el.po'
      - '*be.po'
      - '*nn.po'
      - '*hr.po'
      - '*nb.po'
      - '*sr.po'
      - '*sr@latin.po'
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
