
{
  Carbon Interface

  Dummy implementation. Not tested. 
  Waiting for someone with a Mac to implement it
}

{
  Only a few functions are necessary to compile VirtualTreeView:
}

{.$define HAS_GETTEXTEXTENTEXPOINT}
{.$define HAS_GETTEXTALIGN}
{.$define HAS_GETWINDOWDC}
{.$define HAS_OFFSETRGN}
{.$define HAS_SETBRUSHORGEX}


{$i ../generic/stubs.inc}
{$i ../generic/independentfunctions.inc}
{$i ../generic/unicodefunctions.inc}

